#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SistemaPedidos.Resource", IsApplication=true)]

namespace SistemaPedidos
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020002
			public const int btnClienteListaVolver = 2130837506;
			
			// aapt resource value: 0x7F020000
			public const int btnClieServerSincro = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int btnClieServerVolver = 2130837505;
			
			// aapt resource value: 0x7F020003
			public const int btnDetalleClieNvoPedido = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int btnDetalleClieVolver = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int btnEnviarPedido = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int btnListasPrecioVolver = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int btnListasServerSincronizar = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int btnListasServerVer = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int btnLoginIngresar = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int btnLoginRegistrar = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int btnMnuCliNuevoCliente = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int btnMnuCliSincronizar = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int btnMnuCliVolver = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int btnMnuPedVolver = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int btnMnuPrinVerClientes = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int btnMnuPrinVerListas = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int btnMnuPrinVerPedidos = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int btnMnuPrinVerProductos = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int btnMnuProdVolver = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int btnPedidoActAgregar = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int btnPedidoActFinalizar = 2130837525;
			
			// aapt resource value: 0x7F020017
			public const int btnPedidosListaVolver = 2130837527;
			
			// aapt resource value: 0x7F020016
			public const int btnPedidoVolver = 2130837526;
			
			// aapt resource value: 0x7F020018
			public const int btnPrincManejoTablas = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int btnPrincSincListasPrecio = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int btnPrincSincProd = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int btnPrincSincroClie = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int btnPrincSincroPed = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int btnPrincVerClientes = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int btnPrincVerPedidos = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int btnPrincVerProductos = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int btnProductosPedidoActual = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int btnProductosServerSincronizar = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int btnProductosServerVer = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int btnProductosVolver = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int btnRegistroAceptar = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int btnRegistroCancelar = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int btnVaciarCategorias = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int btnVaciarClientes = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int btnVaciarListasPrecio = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int btnVaciarPedidos = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int btnVaciarProductos = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int btnVariarDetallePed = 2130837547;
			
			// aapt resource value: 0x7F02002D
			public const int lstClienteLista = 2130837549;
			
			// aapt resource value: 0x7F02002C
			public const int lstClieServLista = 2130837548;
			
			// aapt resource value: 0x7F02002E
			public const int lstListasPrecioLista = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int lstListasServerListas = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int lstPedidoActProductos = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int lstPedidosLista = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int lstProductosLista = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int lstProductosServer = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int rd0 = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int rd1 = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int rd2 = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int rdgTiposPedidos = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int spnProductosCategoria = 2130837560;
			
			// aapt resource value: 0x7F02003A
			public const int srchClienteBuscar = 2130837562;
			
			// aapt resource value: 0x7F020039
			public const int srcProductosBusqueda = 2130837561;
			
			// aapt resource value: 0x7F02003B
			public const int textView1 = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public const int textView4 = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int textView6 = 2130837565;
			
			// aapt resource value: 0x7F02003E
			public const int txtClieDomicilioLocalidad = 2130837566;
			
			// aapt resource value: 0x7F02003F
			public const int txtClieNombreRazon = 2130837567;
			
			// aapt resource value: 0x7F020040
			public const int txtClieServerMensaje = 2130837568;
			
			// aapt resource value: 0x7F020041
			public const int txtClieTelefono = 2130837569;
			
			// aapt resource value: 0x7F020042
			public const int txtDetalleClieContacto = 2130837570;
			
			// aapt resource value: 0x7F020043
			public const int txtDetalleClieDireccion = 2130837571;
			
			// aapt resource value: 0x7F020044
			public const int txtDetalleClieNomRazon = 2130837572;
			
			// aapt resource value: 0x7F020045
			public const int txtDetalleClieObservaciones = 2130837573;
			
			// aapt resource value: 0x7F020046
			public const int txtDetalleClieTelefonoCelular = 2130837574;
			
			// aapt resource value: 0x7F020047
			public const int txtFinalizarPedIVA = 2130837575;
			
			// aapt resource value: 0x7F020048
			public const int txtFinalizarPedObservaciones = 2130837576;
			
			// aapt resource value: 0x7F020049
			public const int txtFinalizarPedPtotal = 2130837577;
			
			// aapt resource value: 0x7F02004A
			public const int txtFinalizarPedSubtotal = 2130837578;
			
			// aapt resource value: 0x7F02004B
			public const int txtInputCantMensaje = 2130837579;
			
			// aapt resource value: 0x7F02004C
			public const int txtInputCantProd = 2130837580;
			
			// aapt resource value: 0x7F02004D
			public const int txtListasPrecioNombre = 2130837581;
			
			// aapt resource value: 0x7F02004E
			public const int txtListasPrecioUtilidad = 2130837582;
			
			// aapt resource value: 0x7F02004F
			public const int txtListasServerMensaje = 2130837583;
			
			// aapt resource value: 0x7F020050
			public const int txtLoginMensaje = 2130837584;
			
			// aapt resource value: 0x7F020051
			public const int txtLoginPassword = 2130837585;
			
			// aapt resource value: 0x7F020052
			public const int txtLoginUsuario = 2130837586;
			
			// aapt resource value: 0x7F020053
			public const int txtPedidoCantPrecio = 2130837587;
			
			// aapt resource value: 0x7F020054
			public const int txtPedidoCantProd = 2130837588;
			
			// aapt resource value: 0x7F020055
			public const int txtPedidoCliente = 2130837589;
			
			// aapt resource value: 0x7F020056
			public const int txtPedidoDetalleCodigo = 2130837590;
			
			// aapt resource value: 0x7F020057
			public const int txtPedidoDetalleProducto = 2130837591;
			
			// aapt resource value: 0x7F020059
			public const int txtPedidosItem = 2130837593;
			
			// aapt resource value: 0x7F020058
			public const int txtPedidoTotal = 2130837592;
			
			// aapt resource value: 0x7F02005A
			public const int txtPrincFechaClientes = 2130837594;
			
			// aapt resource value: 0x7F02005B
			public const int txtPrincFechaListas = 2130837595;
			
			// aapt resource value: 0x7F02005C
			public const int txtPrincFechaPedidos = 2130837596;
			
			// aapt resource value: 0x7F02005D
			public const int txtPrincFechaProductos = 2130837597;
			
			// aapt resource value: 0x7F02005E
			public const int txtProductoCodigo = 2130837598;
			
			// aapt resource value: 0x7F02005F
			public const int txtProductoDescripcion = 2130837599;
			
			// aapt resource value: 0x7F020060
			public const int txtProductoPrecio = 2130837600;
			
			// aapt resource value: 0x7F020061
			public const int txtProductoPresentacion = 2130837601;
			
			// aapt resource value: 0x7F020062
			public const int txtProductoPromos = 2130837602;
			
			// aapt resource value: 0x7F020063
			public const int txtProductosServerMensaje = 2130837603;
			
			// aapt resource value: 0x7F020064
			public const int txtRegistroActivo = 2130837604;
			
			// aapt resource value: 0x7F020065
			public const int txtRegistroApellido = 2130837605;
			
			// aapt resource value: 0x7F020066
			public const int txtRegistroContraseña1 = 2130837606;
			
			// aapt resource value: 0x7F020067
			public const int txtRegistroContraseña2 = 2130837607;
			
			// aapt resource value: 0x7F020068
			public const int txtRegistroMensaje = 2130837608;
			
			// aapt resource value: 0x7F020069
			public const int txtRegistroNombre = 2130837609;
			
			// aapt resource value: 0x7F02006A
			public const int txtRegistroUsuario = 2130837610;
			
			// aapt resource value: 0x7F02006B
			public const int txtRegistroVendedor = 2130837611;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int DetalleCliente = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int inputBoxCantProd = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int inputBoxFinalizarPedido = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int ListaClientesServer = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int ListaProductosPedido = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int ListaProductosServer = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int ListasPrecioServer = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int ListViewCliente = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int ListViewCliente_template = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int ListViewListasPrecio = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int ListViewListasPrecio_template = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int ListViewPedidos = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int ListViewPedidos_template = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int ListViewProductos = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int ListViewProductos_template = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int Login = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int Main = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int PaginaConfiguracion = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int PaginaPrincipal = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int PedidoActual = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int PedidoActualDetalle_template = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int Registro = 2130903061;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F040000
			public const int MenuClientes = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int MenuPedidos = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int MenuPrincipal = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int MenuProductos = 2130968579;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
